CREATE TABLE IF NOT EXISTS zabbix_config (
 id INTEGER PRIMARY KEY CHECK (id = 1), url TEXT NOT NULL DEFAULT '', auth_mode TEXT NOT NULL DEFAULT 'token',
 token TEXT NOT NULL DEFAULT '', username TEXT NOT NULL DEFAULT '', password TEXT NOT NULL DEFAULT '', verify_ssl INTEGER NOT NULL DEFAULT 1
);
