import { useEffect, useState } from 'react';
import { zabbixGetConfig, zabbixSaveConfig, zabbixTestConnection, type ZabbixConfig } from '../../lib/tauri';
import './NetclawSettingsTab.css';
export default function ZabbixSettingsTab() {
 const [cfg,setCfg]=useState<ZabbixConfig>({url:'',authMode:'token',token:'',username:'',password:'',verifySsl:true}); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{zabbixGetConfig().then(v=>v&&setCfg(v)).catch(()=>{});},[]);
 const test=async()=>{setBusy(true);try{const r=await zabbixTestConnection(cfg);setStatus(r.message)}catch(e){setStatus(`Test failed: ${String(e)}`)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);try{await zabbixSaveConfig(cfg);setStatus('Configuration saved successfully.')}catch(e){setStatus(`Save failed: ${String(e)}`)}finally{setBusy(false)}};
 return <div className="nc-tab"><div className="nc-header"><h2>Zabbix</h2><p className="nc-subtitle">Connect the Zabbix specialist to one Zabbix 6.4+ or 7.x JSON-RPC endpoint.</p></div><div className="nc-section"><h3>Connection</h3><div className="nc-grid"><label>URL</label><input value={cfg.url} onChange={e=>setCfg({...cfg,url:e.target.value})} placeholder="https://zabbix.example.com/zabbix or .../api_jsonrpc.php"/></div></div><div className="nc-section"><h3>Authentication</h3><div className="nc-grid"><label>Mode</label><select value={cfg.authMode} onChange={e=>setCfg({...cfg,authMode:e.target.value as ZabbixConfig['authMode']})}><option value="token">API token</option><option value="password">Username and password</option></select>{cfg.authMode==='token'?<><label>API token</label><input type="password" value={cfg.token} onChange={e=>setCfg({...cfg,token:e.target.value})}/></>:<><label>Username</label><input value={cfg.username} onChange={e=>setCfg({...cfg,username:e.target.value})}/><label>Password</label><input type="password" value={cfg.password} onChange={e=>setCfg({...cfg,password:e.target.value})}/></>}</div></div><div className="nc-section"><label className="nc-checkbox-label"><input type="checkbox" checked={cfg.verifySsl} onChange={e=>setCfg({...cfg,verifySsl:e.target.checked})}/> Verify SSL certificates</label></div><div className="nc-actions"><button className="nc-btn-primary" disabled={busy} onClick={save}>Save</button><button className="nc-btn-secondary" disabled={busy} onClick={test}>Test Connection</button></div>{status&&<div className="nc-status nc-status--info">{status}</div>}</div>;
}
